/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as AuthenticatedCafeRouteImport } from './routes/_authenticated/cafe'
import { Route as AuthenticatedCalculadoraRouteImport } from './routes/_authenticated/calculadora'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedFoliarRouteImport } from './routes/_authenticated/foliar'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedMilhoSojaRouteImport } from './routes/_authenticated/milho-soja'
import { Route as AuthenticatedMisturaCaldaRouteImport } from './routes/_authenticated/mistura-calda'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCafeRoute = AuthenticatedCafeRouteImport.update({
  id: '/cafe',
  path: '/cafe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalculadoraRoute =
  AuthenticatedCalculadoraRouteImport.update({
    id: '/calculadora',
    path: '/calculadora',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoliarRoute = AuthenticatedFoliarRouteImport.update({
  id: '/foliar',
  path: '/foliar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMilhoSojaRoute = AuthenticatedMilhoSojaRouteImport.update({
  id: '/milho-soja',
  path: '/milho-soja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMisturaCaldaRoute =
  AuthenticatedMisturaCaldaRouteImport.update({
    id: '/mistura-calda',
    path: '/mistura-calda',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/cafe': typeof AuthenticatedCafeRoute
  '/calculadora': typeof AuthenticatedCalculadoraRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/foliar': typeof AuthenticatedFoliarRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/milho-soja': typeof AuthenticatedMilhoSojaRoute
  '/mistura-calda': typeof AuthenticatedMisturaCaldaRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/cafe': typeof AuthenticatedCafeRoute
  '/calculadora': typeof AuthenticatedCalculadoraRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/foliar': typeof AuthenticatedFoliarRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/milho-soja': typeof AuthenticatedMilhoSojaRoute
  '/mistura-calda': typeof AuthenticatedMisturaCaldaRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/definir-senha': typeof DefinirSenhaRoute
  '/_authenticated/cafe': typeof AuthenticatedCafeRoute
  '/_authenticated/calculadora': typeof AuthenticatedCalculadoraRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/foliar': typeof AuthenticatedFoliarRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/milho-soja': typeof AuthenticatedMilhoSojaRoute
  '/_authenticated/mistura-calda': typeof AuthenticatedMisturaCaldaRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/definir-senha'
    | '/cafe'
    | '/calculadora'
    | '/calendario'
    | '/foliar'
    | '/inicio'
    | '/milho-soja'
    | '/mistura-calda'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/definir-senha'
    | '/cafe'
    | '/calculadora'
    | '/calendario'
    | '/foliar'
    | '/inicio'
    | '/milho-soja'
    | '/mistura-calda'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/definir-senha'
    | '/_authenticated/cafe'
    | '/_authenticated/calculadora'
    | '/_authenticated/calendario'
    | '/_authenticated/foliar'
    | '/_authenticated/inicio'
    | '/_authenticated/milho-soja'
    | '/_authenticated/mistura-calda'
    | '/_authenticated/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DefinirSenhaRoute: typeof DefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cafe': {
      id: '/_authenticated/cafe'
      path: '/cafe'
      fullPath: '/cafe'
      preLoaderRoute: typeof AuthenticatedCafeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculadora': {
      id: '/_authenticated/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof AuthenticatedCalculadoraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/foliar': {
      id: '/_authenticated/foliar'
      path: '/foliar'
      fullPath: '/foliar'
      preLoaderRoute: typeof AuthenticatedFoliarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/milho-soja': {
      id: '/_authenticated/milho-soja'
      path: '/milho-soja'
      fullPath: '/milho-soja'
      preLoaderRoute: typeof AuthenticatedMilhoSojaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mistura-calda': {
      id: '/_authenticated/mistura-calda'
      path: '/mistura-calda'
      fullPath: '/mistura-calda'
      preLoaderRoute: typeof AuthenticatedMisturaCaldaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCafeRoute: typeof AuthenticatedCafeRoute
  AuthenticatedCalculadoraRoute: typeof AuthenticatedCalculadoraRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedFoliarRoute: typeof AuthenticatedFoliarRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedMilhoSojaRoute: typeof AuthenticatedMilhoSojaRoute
  AuthenticatedMisturaCaldaRoute: typeof AuthenticatedMisturaCaldaRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCafeRoute: AuthenticatedCafeRoute,
  AuthenticatedCalculadoraRoute: AuthenticatedCalculadoraRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedFoliarRoute: AuthenticatedFoliarRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedMilhoSojaRoute: AuthenticatedMilhoSojaRoute,
  AuthenticatedMisturaCaldaRoute: AuthenticatedMisturaCaldaRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DefinirSenhaRoute: DefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
